### PR TITLE
fix: n and N fail

### PR DESCRIPTION
**Pull request by MirrorCY**
## Summary by CodeRabbit

- **New Features**
	- Improved handling of model and preset selections with clearer user input management.
	
- **Bug Fixes**
	- Streamlined the control flow for setting room visibility, improving the handling of user input conditions.

These changes enhance the overall user experience by ensuring that model and preset selections are more intuitive and that room visibility behaves as expected under various scenarios.

### CODE REVIEW

**Comment by MirrorCY** [comment]
image

**Comment by dingyi222666** [comment]
应该再优化下，预先检测一次输入，无效输入就返回上次设置内容，还有几处地方都可以改

**Comment by dingyi222666** [comment]
或者等下我向 pr 里面加吧

**Comment by MirrorCY** [comment]
我**完全**修错了，等会我改改

**Comment by MirrorCY** [comment]
睡前还是不要写东西为妙

**Review by dingyi222666 — APPROVED** [review]

**Pull request merged**
